### ISSUE TITLE
[ERROR] [nuxt] [request error] [unhandled] [500] Invalid URL string.

### ISSUE THREAD

**Issue by Keyvitia** [nuxt-modules/kinde#112]
Just follow the instructions to add the kinde module to a Nuxt Hub template. After deployed to the cloudflare, calling the '/api/login' ended up wit the the following error:
```
GET 500 /api/login
[nuxt] [request error] [unhandled] [500],Invalid URL string.
  at AuthorizationCode.<anonymous> (chunks/runtime.mjs:1:168189)  
  at chunks/runtime.mjs:1:167114  
  at Object.next (chunks/runtime.mjs:1:167219)  
  at fulfilled (chunks/runtime.mjs:1:165881)
``` 
It worked completely fine with dev server. Have been trying with build configurations, but no luck. I couldn't figure out if this is the module issue or the nitro server issue.

Package details:
```
"@nuxt/eslint": "^0.3.13",
"@nuxthub/core": "^0.6.11",
"@nuxtjs/kinde": "^0.1.10",
"h3-zod": "^0.5.3",
"nuxt": "^3.12.1",
"zod": "^3.23.8",
"typescript": "5.4.5"
```

**Comment by Keyvitia** [comment]
I have recently found out a similar issue, #99, has been reported and resolved. The solution from this issue solved my problem too.
