### ISSUE TITLE
/api/login | route cannot found after build project

### ISSUE THREAD

**Issue by mertefecerit** [nuxt-modules/kinde#211]
when run the project after build getting 500 error on nuxt server side, this logic working on dev and preview mode but not build.

```batch
[nuxt] [request error] [unhandled] [500] Invalid URL
[Vue Router warn]: No match found for location with path "/api/login"
```

Our Middleware (work on preview and dev mode not build)
```ts
export default defineNuxtRouteMiddleware(async () => {
    const client = useKindeClient();
    if (client) {
        const isAuth = await client.isAuthenticated();
        if (isAuth) {
            const token = await client.getToken();
            useState('token', () => token);
            return true;
        }else{
            useState('token', () => null);
            return navigateTo('/api/login', {external:true});
        }
    }
})
```

Testing these links (work on preview and dev mode not build)
```vue
<LoginLink to="/api/login" external>login</LoginLink>
<RegisterLink to="/api/register" external>register</RegisterLink>


<client-only>
  <LoginLink to="/api/login" external>login</LoginLink>
  <RegisterLink to="/api/register" external>register</RegisterLink>
<client-only>
```

**Comment by mertefecerit** [comment]
> I'm experiencing the same thing. Dev and Preview runs like a charm but as soon as it's built and run as in production it generates 500 error.
> 
> ```
> [request error] [unhandled] [GET] http://localhost:3000/api/login
>  TypeError: Invalid URL
>     at new URL (node:internal/url:818:25)
>     ... 3 lines matching cause stack trace ...
>     at fulfilled (file:///project/.output/server/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthorizationCode.js:19:58) {
>   cause: TypeError: Invalid URL
>       at new URL (node:internal/url:818:25)
>       at AuthorizationCode.<anonymous> (file:///project/.output/server/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthorizationCode.js:114:35)
>       at step (file:///project/.output/server/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthorizationCode.js:47:23)
>       at Object.next (file:///project/.output/server/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthorizationCode.js:28:53)
>       at fulfilled (file:///project/.output/server/node_modules/@kinde-oss/kinde-typescript-sdk/dist/sdk/oauth2-flows/AuthorizationCode.js:19:58) {
>     code: 'ERR_INVALID_URL',
>     input: '/oauth2/auth'
>   },
>   statusCode: 500,
>   fatal: false,
>   unhandled: true,
>   statusMessage: undefined,
>   data: undefined
> }
> [Vue Router warn]: No match found for location with path "/api/login"
> [Vue Router warn]: No match found for location with path "/api/login"
> ```

You need to fill the kinde section in the nuxt.config.ts file with the data in env. During the build phase, it reads the kinde property under nuxt config.

```js
export default defineNuxtConfig({
  ...//other configs
  kinde: {
    authDomain: process.env.NUXT_KINDE_AUTH_DOMAIN,
    clientId: process.env.NUXT_KINDE_CLIENT_ID,
    clientSecret: process.env.NUXT_KINDE_CLIENT_SECRET,
    redirectURL: process.env.NUXT_KINDE_REDIRECT_URL,
    logoutRedirectURL: process.env.NUXT_KINDE_LOGOUT_REDIRECT_URL,
    postLoginRedirectURL: process.env.NUXT_KINDE_POST_LOGIN_REDIRECT_URL,
    password: process.env.NUXT_KINDE_PASSWORD,
  },
})
```
